### ISSUE TITLE
Escolha de nomes para as funções de modelo

### ISSUE THREAD

**Issue by augustoicaro** [EndersonMarques/nodets-web-01#1]
No modelo você definiu o tipo `Pet` com as suas propriedades par abstrair o objeto pet. Em seguida você define hardcoded quais são os pets possíveis na aplicação. E por fim você cria um objeto com funções para manipular esses dados que você chama de `Pet` que foi o mesmo que você usou para representar um objeto do tipo pet. No fim tendo:

* Pet -> como um tipo, podendo usar `let dog: Pet;`
* Pet -> como uma variável objeto, podendo usar `const dogs = Pet.getFromType('dog');`

Nessa condição fica confuso dar o nome de `Pet` para o objeto de funções, onde eu sugiro trocar por `petDB` ou `pets`. Geralmente usamos a letra inicial maiúscula para determinar que é uma classe, um tipo, um construtor, nesse caso como é um objeto de funções ele não deveria ter a primeira letra maiúscula.

**Comment by EndersonMarques** [comment]
Entendi !!! Obrigado !!! Realmente faz mais sentido dessa forma quando o
sistema ficar maior

Em sáb., 17 de jul. de 2021 15:41, Augusto Ícaro Farias da Cunha <
***@***.***> escreveu:

**Comment by EndersonMarques** [comment]
Outra coisa que fiquei meio confuso foi fazer as funções no model sendo que
pra mim isso deveria ser no controller, só que em todos os exemplos que
pesquisei as funções ficavam no model, então acabei fazendo dessa forma,
funções do tipo getAll e etc. Pelo menos no Edge quando eu fazia (copiava
de o exemplo de outro haha) um CURD em .Net, os models ficam numa pasta
chamada Domain e lá era só declarado o objeto em si e nos controlleres que
ficavam as funções de getAll e etc. Isso é comum por ser em js/ts? Ou é
porque ainda não existe um padrão a ser seguido nessas linguagem? ( vi uma
resposta assim no stackoverflow kk)

Em sáb., 17 de jul. de 2021 15:42, Enderson Marques de Matos Filho <
***@***.***> escreveu:

**Comment by augustoicaro** [comment]
Essa é uma boa pergunta. Para evitar essa situação algumas pessoas expandem o modelo de MVC criando um viewModel que guarda justamente essas função deixando de fato o modelo somente com as definições de modelo. Mas na proposta inicial do MVC o model faz todo esse processo de aquisição dos dados, talvez colocar num arquivo diferente na mesma pasta.

Eu também estranhei quando eu vi, dei uma revisada no conceito e era isso mesmo. Então não falei a nada a respeito.
No Angular temos um cara bem especifico para tratar esse tipo e coisa, que chamamos de `Serviço`. No serviço colocamos todas as funções de manipulação dos dados e o modelo de fato só tem a definição de modelo.

**Comment by EndersonMarques** [comment]
Compreendi, ótimo, agora estou curioso para ver angular haha

Em sáb., 17 de jul. de 2021 16:21, Augusto Ícaro Farias da Cunha <
***@***.***> escreveu:
